services:
  mongo:
    image: mongo:7
    container_name: carSellingMongo_dev
    command: ["mongod", "--port", "27017", "--bind_ip_all"]
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    networks:
      - myDynamicNetwork
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://carSellingMongo_dev:27017/test --quiet 2>&1 || exit 1
      interval: 6s
      timeout: 5s
      retries: 20
      start_period: 20s

  mongo-express:
    image: mongo-express:latest
    container_name: carSellingMongoExpress_dev
    ports:
      - 8093:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=carSellingMongo_dev
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - myDynamicNetwork

  backend:
   container_name: carSellingBackend_dev
   build:
      context: ./backend
      dockerfile: Dockerfile
   ports:
     - '6003:3003'
   volumes:
     - ./backend/public/invoices:/app/public/invoices
     - ./backend/public/uploads:/app/public/uploads
   depends_on:
     mongo:
       condition: service_healthy
   restart: always
   networks:
     - myDynamicNetwork
   environment:
     - MONGO_URI=mongodb://carSellingMongo_dev:27017/Drivezy_Mix
     - PORT=3003
     - SECRET=Drivezy_Mix
     - SERVICEPATH=https://parsa-akbari.strangled.net/api/v1/

  frontend:
     container_name: carSellingFrontend_dev
     build:
         context: ./frontend
         dockerfile: Dockerfile
         args:
           - NEXT_PUBLIC_BACKEND_URL=https://parsa-akbari.strangled.net/api/v1/
     ports:
       - '6000:3000'
     networks:
       - myDynamicNetwork
     depends_on:
       - backend
     restart: unless-stopped
     environment:
       - FRONTEND_PORT=3000
       - NEXT_PUBLIC_BACKEND_URL=https://parsa-akbari.strangled.net/api/v1/

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - myDynamicNetwork

networks:
  myDynamicNetwork:
    name: Drivezy_MixNetwork
    driver: bridge

volumes:
  caddy_data:
